import type { Staff, Client, Product } from "./types";

// Constants — taxes du Québec, calculées séparément (certains produits n'ont
// que la TPS depuis la loi retirant la TVQ sur les pâtisseries/viennoiseries).
export const TPS_RATE = 0.05; // Taxe fédérale (TPS)
export const TVQ_RATE = 0.09975; // Taxe provinciale (TVQ)
export const TAX_RATE = TPS_RATE + TVQ_RATE; // 0.14975 (combiné, pour l'affichage)

/**
 * Mode de taxe d'un produit, déduit de `taxMode` (both/gst_only/none) avec repli
 * sur l'ancien booléen `hasTaxes`. Renvoie les taux TPS/TVQ à appliquer.
 */
export function itemTaxRates(item: { taxMode?: string; hasTaxes?: boolean }): {
  tps: number;
  tvq: number;
} {
  const mode =
    item.taxMode === "both" || item.taxMode === "gst_only" || item.taxMode === "none"
      ? item.taxMode
      : item.hasTaxes === false
        ? "none"
        : "both";
  if (mode === "both") return { tps: TPS_RATE, tvq: TVQ_RATE };
  if (mode === "gst_only") return { tps: TPS_RATE, tvq: 0 };
  return { tps: 0, tvq: 0 };
}

// ✅ CORRECTION: Staff IDs sont des numbers selon types.d.ts
export const MOCK_STAFF: Staff[] = [
  {
    id: 1,
    firstName: "Marie",
    lastName: "Dubois",
    email: "marie.dubois@mariusetfanny.com",
    phone: "514-555-0101",
    location: "Montreal",
    department: "customer_service",
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    firstName: "Jean",
    lastName: "Tremblay",
    email: "jean.tremblay@mariusetfanny.com",
    phone: "450-555-0202",
    location: "Laval",
    department: "kitchen_staff",
    status: "active",
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
  },
  {
    id: 3,
    firstName: "Sophie",
    lastName: "Laurent",
    email: "sophie.laurent@mariusetfanny.com",
    phone: "514-555-0303",
    location: "Montreal",
    department: "customer_service",
    status: "suspended",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-01T10:00:00Z",
  },
  {
    id: 4,
    firstName: "Pierre",
    lastName: "Martin",
    email: "pierre.martin@mariusetfanny.com",
    phone: "450-555-0404",
    location: "Laval",
    department: "customer_service",
    status: "active",
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-02-10T10:00:00Z",
  },
];

export const LOCATIONS = [
  { value: "Montreal", label: "Montréal" },
  { value: "Laval", label: "Laval" },
];

export const DEPARTMENTS = [
  { value: "customer_service", label: "Service Client" },
  { value: "kitchen_staff", label: "Personnel de Cuisine" },
  { value: "delivery_driver", label: "Livreur" },
];

// ✅ CORRECTION: Client IDs sont des numbers, Address IDs sont des numbers, mais Order IDs sont des strings
export const MOCK_CLIENTS: Client[] = [
  {
    id: 1,
    firstName: "Marie",
    lastName: "Dubois",
    email: "marie.dubois@example.com",
    phone: "514-555-0123",
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    addresses: [
      {
        id: 1,
        type: "billing",
        street: "123 Rue Sainte-Catherine",
        city: "Montreal",
        province: "QC",
        postalCode: "H3B 1A1",
        isDefault: true,
      },
      {
        id: 2,
        type: "shipping",
        street: "123 Rue Sainte-Catherine",
        city: "Montreal",
        province: "QC",
        postalCode: "H3B 1A1",
        isDefault: true,
      },
    ],
    orders: [
      {
        id: "ORD-2024-001",  // ✅ STRING
        orderNumber: "ORD-2024-001",
        clientId: 1,
        client: {} as any,
        orderDate: "2024-01-15T14:30:00Z",
        pickupDate: "2024-01-18T10:00:00Z",
        pickupLocation: "Montreal",
        deliveryType: "pickup",
        items: [],
        subtotal: 80.0,
        taxAmount: 9.99,
        deliveryFee: 0,
        total: 89.99,
        depositAmount: 44.99,
        depositPaid: true,
        balancePaid: true,
        paymentStatus: "paid",
        status: "completed",
        source: "online",
        createdAt: "2024-01-15T14:30:00Z",
        updatedAt: "2024-01-18T10:00:00Z",
      },
      {
        id: "ORD-2024-045",  // ✅ STRING
        orderNumber: "ORD-2024-045",
        clientId: 1,
        client: {} as any,
        orderDate: "2024-02-03T11:20:00Z",
        pickupDate: "2024-02-05T15:00:00Z",
        pickupLocation: "Montreal",
        deliveryType: "pickup",
        items: [],
        subtotal: 110.0,
        taxAmount: 15.5,
        deliveryFee: 0,
        total: 125.5,
        depositAmount: 62.75,
        depositPaid: true,
        balancePaid: true,
        paymentStatus: "paid",
        status: "completed",
        source: "phone",
        createdAt: "2024-02-03T11:20:00Z",
        updatedAt: "2024-02-05T15:00:00Z",
      },
    ],
  },
  {
    id: 2,
    firstName: "Jean",
    lastName: "Tremblay",
    email: "jean.tremblay@example.com",
    phone: "514-555-0456",
    status: "placeholder",
    createdAt: "2024-02-10T09:30:00Z",
    updatedAt: "2024-02-10T09:30:00Z",
    addresses: [],
    orders: [
      {
        id: "ORD-2024-102",  // ✅ STRING
        orderNumber: "ORD-2024-102",
        clientId: 2,
        client: {} as any,
        orderDate: "2024-02-10T09:30:00Z",
        pickupDate: "2024-02-12T12:00:00Z",
        pickupLocation: "Laval",
        deliveryType: "pickup",
        items: [],
        subtotal: 40.0,
        taxAmount: 5.0,
        deliveryFee: 0,
        total: 45.0,
        depositAmount: 22.5,
        depositPaid: true,
        balancePaid: true,
        paymentStatus: "paid",
        status: "completed",
        source: "in_store",
        createdAt: "2024-02-10T09:30:00Z",
        updatedAt: "2024-02-12T12:00:00Z",
      },
    ],
  },
  {
    id: 3,
    firstName: "Sophie",
    lastName: "Martin",
    email: "sophie.martin@example.com",
    phone: "450-555-0789",
    status: "active",
    createdAt: "2024-01-20T16:45:00Z",
    updatedAt: "2024-01-20T16:45:00Z",
    addresses: [
      {
        id: 3,
        type: "billing",
        street: "456 Boulevard des Laurentides",
        city: "Laval",
        province: "QC",
        postalCode: "H7G 2V1",
        isDefault: true,
      },
    ],
    orders: [
      {
        id: "ORD-2024-078",  // ✅ STRING
        orderNumber: "ORD-2024-078",
        clientId: 3,
        client: {} as any,
        orderDate: "2024-02-01T13:15:00Z",
        pickupDate: "2024-02-15T14:00:00Z",
        pickupLocation: "Montreal",
        deliveryType: "delivery",
        deliveryAddress: {
          id: 3,
          type: "shipping",
          street: "456 Boulevard des Laurentides",
          city: "Laval",
          province: "QC",
          postalCode: "H7G 2V1",
          isDefault: true,
        },
        items: [],
        subtotal: 185.0,
        taxAmount: 10.75,
        deliveryFee: 15.0,
        total: 210.75,
        depositAmount: 105.38,
        depositPaid: true,
        balancePaid: false,
        paymentStatus: "deposit_paid",
        status: "in_production",
        source: "online",
        createdAt: "2024-02-01T13:15:00Z",
        updatedAt: "2024-02-10T09:00:00Z",
      },
    ],
  },
  {
    id: 4,
    firstName: "Pierre",
    lastName: "Lavoie",
    email: "pierre.lavoie@example.com",
    phone: "438-555-0321",
    status: "placeholder",
    createdAt: "2024-02-05T11:00:00Z",
    updatedAt: "2024-02-05T11:00:00Z",
    addresses: [],
    orders: [],
  },
];

// ✅ CORRECTION: Product IDs sont des numbers selon types.d.ts
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "La Marguerite (6 pers.)",
    category: ["Gâteaux"],
    price: 37.5,
    available: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 5,
    description: "Gâteau signature aux saveurs délicates",
    preparationTimeHours: 48,
    productionType: "patisserie" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    name: "Tarte Citron Meringuée",
    category: ["Gâteaux"],
    price: 29.95,
    available: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 3,
    description: "Tarte au citron avec meringue italienne",
    preparationTimeHours: 24,
    productionType: "patisserie" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 3,
    name: "Baguette Tradition",
    category: ["Pains"],
    price: 3.5,
    available: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 20,
    description: "Pain tradition français",
    preparationTimeHours: undefined,
    productionType: "cuisinier" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 4,
    name: "Pain Campagne Bio",
    category: ["Pains"],
    price: 4.8,
    available: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 10,
    description: "Pain de campagne bio au levain",
    preparationTimeHours: undefined,
    productionType: "cuisinier" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 5,
    name: "Croissant Pur Beurre",
    category: ["Viennoiseries"],
    price: 2.2,
    available: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    description: "Croissant artisanal au beurre",
    preparationTimeHours: undefined,
    productionType: "patisserie" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 6,
    name: "Pain au Chocolat",
    category: ["Viennoiseries"],
    price: 2.4,
    available: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 30,
    description: "Pain au chocolat avec chocolat belge",
    preparationTimeHours: undefined,
    productionType: "patisserie" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 7,
    name: "Macarons Assortis (12 pcs)",
    category: ["Chocolats"],
    price: 24.0,
    available: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 10,
    description: "Boîte de 12 macarons aux saveurs variées",
    preparationTimeHours: 72,
    productionType: "patisserie" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 8,
    name: "Chocolats Pralinés (250g)",
    category: ["Chocolats"],
    price: 18.5,
    available: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 15,
    description: "Assortiment de chocolats pralinés maison",
    preparationTimeHours: 48,
    productionType: "patisserie" as const,
    targetAudience: "clients" as const,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
];

export const CATEGORIES = [
  "Gâteaux",
  "Pains",
  "Viennoiseries",
  "Chocolats",
  "Boîte à lunch",
  "Salade repas",
  "Plateau repas",
  "Option végétarienne",
  "À la carte",
  "St-Valentin",
];
